export const translationStrings = {
  en: {
    about: 'About',
    available: 'Available for',
    copied: 'Copied',
    install: 'Install',
    langs: 'Languages',
    lsup: 'Languages supported',
    more: 'Know more',
    palette: 'Palette',
    screenshots: 'Screenshots',
    slogan: 'A theme with sober colors, hence the name',
  },
  pt: {
    about: 'Sobre',
    available: 'Disponível para',
    copied: 'Copiado',
    install: 'Instalar',
    langs: 'Linguagens',
    lsup: 'Linguagens suportadas',
    more: 'Saiba mais',
    palette: 'Paleta',
    screenshots: 'Telas',
    slogan: 'Um tema com cores sóbrias, daí o nome',
  },
};
